### ISSUE TITLE
npm release pipeline

### ISSUE THREAD

**Issue by norkator** [SKR301/Metric-Clock#21]
Do you want pipeline for this?

I have templates ready if needed.

**Comment by norkator** [comment]
If yes, then you need npm account and secret token for pipeline.

**Comment by SKR301** [comment]
Sure, but after some automatic testing. I'll be in touch.

**Comment by norkator** [comment]
> Sure, but after some automatic testing. I'll be in touch.

I can start writing tests today.

**Comment by SKR301** [comment]
> > Sure, but after some automatic testing. I'll be in touch.
> 
> I can start writing tests today.


Do you know what are the test cases?

**Comment by norkator** [comment]
> > > Sure, but after some automatic testing. I'll be in touch.
> > 
> > 
> > I can start writing tests today.
> 
> Do you know what are the test cases?
> 
> `Assert.assertEqual(true,true);`

No way! I can make real tests.

**Comment by SKR301** [comment]
Well, go for it👍
