### ISSUE TITLE
Make a library for same

### ISSUE THREAD

**Issue by SKR301** [SKR301/Metric-Clock#3]
- [x] help
- [x] parse arguments
- [x] description
- [ ] readme
- [x] formats [0-9] only

CONVERSION:
- [x] metric->normal [time]
- [x] normal->metric [time]
- [x] metric->normal [date]
- [x] normal->metric [date]

DISPLAY:
- [x] current metric time
- [x] current time with format

ARITHMETIC:
- [x] add date
- [x] add time
- [x] sub date
- [x] sub time

**Comment by norkator** [comment]
Whats the end goal for this repository?

**Comment by SKR301** [comment]
A website/lib to show metric time. LOL
Maybe I'll find a better use for it someday
